name: "CI/CD_{{SERVICE}}_master"

on:
  push:
    branches: [ develop ]
    paths:
      - "services/{{SERVICE}}/**"
      - ".github/workflows/{{SERVICE}}_master.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: {{SERVICE}}

    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@master

      - name: Install 🔧
        run: npm ci
      
      - name: Lint 🧐
        run: npm run lint

      - name: Test 🚨
        run: npm test